### ISSUE TITLE
version 3.6.3 and higher causing bounding box issues

### ISSUE THREAD

**Issue by arianwen27** [d4rkc0d3r/d4rkAvatarOptimizer#105] opened 2024-05-25 23:30 UTC
3.6.2 works as normal. 3.6.3 and 3.6.4 causes my avatar's bounding box to become (143.89, 208.17, 183.64), way too high and causes avatar rating to become very poor. Disabling "merge skinned meshes" allows the bounding box to be a normal size. 
Only happens on some of my avatars. Winterpaws are fine, my RexEvolved has this issue. Though since it only happened after version 3.6.2, I don't know if a way to fix it on my end.

**Comment by d4rkc0d3r** [comment] 2024-05-26 13:38
It's probably caused by models with bad export settings that as a result have an armature scale of 100 in unity instead of 1. I'll look into it and probably fix it soon-ish if it is that.

As a side note: The only thing that happens if bounding box is too large is that your displayed performance rank gets very poor. Performance blocking doesn't actually care about the bounding box size and will still display your avatar and not the fallback.

**Comment by arianwen27** [comment] 2024-05-26 21:25
Little update, 3.6.3 and 3.6.4 also cause the WPThong asset to become about 50x bigger in the front than it's supposed to be
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/47794936/10ac00f5-057d-4a80-960b-42ccdf8aad40)
Using 3.6.2 and lower makes it look normally sized again

**Comment by aspwil** [comment] 2024-05-26 23:28
im also experiencing this issue

**Comment by aspwil** [comment] 2024-05-26 23:34
before and after

![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/65490493/ea213e6a-e9bb-47d7-b927-cc56af198ed5)

![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/65490493/696eab24-f4fb-4716-ba92-b90ef20092e1)

**Comment by arianwen27** [comment] 2024-05-27 19:48
I also found my hyenid model's bounding box goes up by 50 in each section

**Comment by d4rkc0d3r** [comment] 2024-06-05 19:30
I changed it to only set the scale of bones that have scaling animations to 1 instead of all bones. That should make it behave much more similar to pre 3.6.2 while fixing the original bug of objects being scaled down by default.
Please report back if these issues are now gone with 3.7.0

**Comment by CorneliusCornbread** [comment] 2024-06-06 01:40
Just commenting to say I _was_ having this exact issue on my avatar. Just updated and it's been resolved. Great work!

**Comment by d4rkc0d3r** [comment] 2024-06-08 20:05
I'll close this now as it seems solved. If there are any more problems just make a new issue.

**Closed by d4rkc0d3r** 2024-06-08 20:05 UTC
