### ISSUE TITLE
d4rk's inspector breaks components inserted below it when an exception is thrown during render

### ISSUE THREAD

**Issue by SenkyDragon** [d4rkc0d3r/d4rkAvatarOptimizer#104] opened 2024-05-24 06:48 UTC
Add a d4rk optimizer component, then add any component to the same object afterward, and the inspector will be broken until refocused.

![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/117542830/56248590-6461-44ba-813f-2d5004fa62d2)

**Comment by d4rkc0d3r** [comment] 2024-05-24 13:02
Doesn't happen for me. Layouting issues can often be caused by another tool and are really hard to debug. I blame something else overwriting one of the built in gui styles unless there is more info that directly points to what I might be doing wrong here.

**Comment by SenkyDragon** [comment] 2024-05-24 20:37
Update: This happened because of #102 . Seems that if an exception is thrown during the rendering of the editor, that's what causes the inspector to blow up. Not sure if there's a good way to resolve this issue (aside from wrapping.... basically everything individually in a try catch), but it is a good reason for d4rk to be using UIElements (which has been available since at least 2017) rather than UGUI. It would probably require a pretty big rewrite of the editor though.

**Comment by d4rkc0d3r** [comment] 2024-05-24 22:06
Thanks for the info. That actually makes a lot of sense.
I'll close this as won't fix though as its really just making crashes worse. But crashes shouldn't happen to begin with.
I also have no plans to rewrite the editor to using UIElements.

**Closed by d4rkc0d3r** 2024-05-24 22:06 UTC
